### ISSUE TITLE
持续关注中，希望可以不间断更新……

### ISSUE THREAD

**Issue by yuzhewo** [bennyhuo/Kotlin-Tutorials#1]
大神辛苦了，感谢你的付出！

**Comment by bennyhuo** [comment]
谢谢关注~会持续更新哒，今天会录制第7集，上周项目有点儿紧，没抽出空。周末第7集试录了一遍感觉效果不行，今天再录一次，本周之内就会发~

**Comment by bennyhuo** [comment]
目前想做到固定时间更新还是有一些困难，不过后续我会随时更新下一集的制作进展，一定会持续更新下去的~

**Comment by bennyhuo** [comment]
关注微信公众号 Kotlin，每周一会推送最新一期视频的更新信息哈~
