### ISSUE TITLE
关于kotlin交流群

### ISSUE THREAD

**Issue by skyshenfu** [bennyhuo/Kotlin-Tutorials#12]
您好，拜读了您的作品，获益匪浅。本想加入您的qq交流群，但是有一个叫Dado杰的管理员拒绝了申请，并且附言‘好歹百度一下’，请问加群有什么硬性条件么？

**Comment by wargame22** [comment]
进群会有个问题，比较简单，但是还是需要查一查，回答一下，否则是进不去的。

skyshenfu <notifications@github.com>于2017年5月22日周一 下午5:18写道：

**Comment by bennyhuo** [comment]
就回答个问题就好啦，主要是培训班的，想以此谋利的，以及伸手党把群里的小伙伴搞得晕头转向，就弄个问题稍微确认诚意，不要误会哈。

**Comment by bennyhuo** [comment]
如果没有学习过，搜一下，正确回答下问题就可以啦。问题都是不太难的，并没有把大家拒于门外之意，希望理解。
