### ISSUE TITLE
Kotlin从入门到『放弃』系列第13期 DaggerRESTFulComponent

### ISSUE THREAD

**Issue by specialshoot** [bennyhuo/Kotlin-Tutorials#17]
DaggerRESTFulComponent类在net.println.kt13包中没有给出

**Comment by bennyhuo** [comment]
这个不是问题哈，建议你先去了解 dagger。

**Comment by specialshoot** [comment]
dagger我按照官方文档配置了,然而还是没有生成dagger类,将您的项目直接拉下来编译也是没有过.编译器是idea,java用的是java8,具体配置如下:
`
group 'com.han'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.1.2-2'
    ext.retrofit_version = '2.3.0'
    ext.dagger_version = '2.11'

    repositories {
        jcenter()
//        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'java'
apply plugin: 'kotlin'
apply plugin: 'kotlin-kapt'

sourceCompatibility = 1.8

repositories {
    jcenter()
//    mavenCentral()
}

sourceSets {
    main.java.srcDirs += [file("$buildDir/generated/source/kapt2/main")]
}

//kapt {
//    generateStubs = true
//}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    compile "io.reactivex.rxjava2:rxjava:2.1.0"
    compile "com.google.code.gson:gson:2.8.1"
    compile "com.squareup.retrofit2:retrofit:$retrofit_version"
    compile "com.squareup.retrofit2:converter-gson:$retrofit_version"
    compile "com.squareup.retrofit2:adapter-rxjava:$retrofit_version"
    compile "com.google.dagger:dagger:${dagger_version}"
    kapt "com.google.dagger:dagger-compiler:${dagger_version}"
    provided 'org.glassfish:javax.annotation:10.0-b28'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
`
