### ISSUE TITLE
请问kotlin在idea中如何快速生成变量名

### ISSUE THREAD

**Issue by immadolf** [bennyhuo/Kotlin-Tutorials#19]
老师你好，当我使用idea编写java代码的时候，由于是类型在前，所以idea会自动的提示我几个可能的变量名(如下图)，请问在kotlin中是否有这样的功能呢？
![](https://ooo.0o0.ooo/2017/06/27/595213bcca0a3.gif)

**Comment by bennyhuo** [comment]
因为类型后置，所以还不太一样，提示的效果可能是：

val i (提示你输入 int: Int) 
val s(提示你输入 string: String)
val x(提示你输入xxx: Long，这个主要是你之前输入过这个变量才会这样提示)
