### ISSUE TITLE
咨询一个问题

### ISSUE THREAD

**Issue by yangwuan55** [bennyhuo/Kotlin-Tutorials#20]
现在我在做一个sdk，编译出aar给客户程序用。我将sdk的library项目改成kotlin支持后，发现在xml里不能写中文拼接的textview了
像这样：
![image](https://user-images.githubusercontent.com/5218120/28060738-b54a1988-665a-11e7-9d8e-4155e6f2ab29.png)

显示出来会是乱码：

![image](https://user-images.githubusercontent.com/5218120/28060757-c3d27f4a-665a-11e7-81db-8c7aab2c152b.png)

如果直接依赖library项目不会有乱码问题，但是如果用打出来的aar包就会有这个问题。
求大神指教啊/(ㄒoㄒ)/~~

**Comment by bennyhuo** [comment]
我没有遇到过类似的问题。建议你到 StackOverflow 提问哈。另外，这个问题可能跟项目本身没有太直接的关系，我先关闭了~
