### ISSUE TITLE
DaggerRESTFulComponent.kt is not founded

### ISSUE THREAD

**Issue by gorpher** [bennyhuo/Kotlin-Tutorials#21]
DaggerRESTFulComponent.kt not in the kt13 folder .

**Comment by gorpher** [comment]
在我的generated文件夹下没有生成kapt2文件夹 这里怎么弄的?

**Comment by bennyhuo** [comment]
视频的版本比较老了哈，现在貌似是 kapt ，你看看有没有

**Comment by bennyhuo** [comment]
issue 先关闭了哈，有问题再打开~~
