### ISSUE TITLE
建议试试在线markdown：http://md.aclickall.com

### ISSUE THREAD

**Issue by garyyan** [bennyhuo/Kotlin-Tutorials#23]
你文档中说的公众号中的代码块的问题，建议试试在线markdown：http://md.aclickall.com
解决markdown在公众号遇到的种种问题
支持几十种代码块样式，
支持一键排版和自定义样式
最主要还是免费的

**Comment by bennyhuo** [comment]
感谢！我这段时间一直在用 http://md.barretlee.com/ ，以后两个对比着用，哈哈
