### ISSUE TITLE
有点贵。

### ISSUE THREAD

**Issue by iwh718** [bennyhuo/Kotlin-Tutorials#24]
想看看关于kt反射的。

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by bennyhuo** [comment]
熟悉 Java 反射的话，Kotlin 反射也不过就是加了一些特性的支持，思路基本一致，关注我公众号里面有几篇提到反射的文章，另外也可以看下 https://github.com/enbandari/ObjectPropertyDelegate 和 https://github.com/enbandari/RetroApollo-Android，这两个都是课程里开发用的框架，你可以直接看源码就行了。
