### ISSUE TITLE
Gradle 迁移 KTS 系列视频

### ISSUE THREAD

**Issue by bennyhuo** [bennyhuo/Kotlin-Tutorials#25]
前不久开源了一个小项目 [Android-LuaJavax](https://github.com/bennyhuo/Android-LuaJavax)，在改造 Gradle 脚本的时候也同时看到群里有不少小伙伴在问 KTS 编写 Gradle 脚本的问题，于是想要做几个视频来介绍下 Gradle 脚本从 Groovy 到 Kotlin 需要掌握哪些内容。

- [x] [你的 Gradle脚本究竟是什么？](https://www.bilibili.com/video/BV18K4y1D7Yb/)
- [x] [你的 Gradle 脚本是怎么运行起来的？](https://www.bilibili.com/video/BV1ep4y1h7qU/)
- [x] [Gradle Project 的属性都是哪里来的？](https://www.bilibili.com/video/BV16h411D77Q/)
- [x] [Gradle Task 创建的特殊语法](https://www.bilibili.com/video/BV1ib4y1D74X/)
- [x] [快速迁移 Gradle 脚本至 KTS](https://www.bilibili.com/video/BV1Kf4y1p7zq/)
- [x] [番外：如何调试 Gradle 源码](https://www.bilibili.com/video/BV1m54y1L7vK)
- [x] [如何为 Gradle 的 KTS 脚本添加扩展？](https://www.bilibili.com/video/BV1BU4y1b7Wk/) 预计 2021.5.2  18:00 在 B 站发布

大家如果有什么想法，也欢迎加入 催更群：966752510 一起讨论。

**Comment by bennyhuo** [comment]
5 的文本已经写完，6 不用写文本。目前在研究 7，如果不理想，就不解锁 7 了~~

**Comment by Richyeoh** [comment]
`` 我要Compiler的Ir教程 ``

**Comment by bennyhuo** [comment]
> `我要Compiler的Ir教程`

你这个我后面再开个 issue

**Comment by bennyhuo** [comment]
7 基本上调研清楚了，虽然不是很美，不过对于了解 Kotlin DSL 的运行机制有好处，所以还是作为这个系列的收尾放出来吧。

**Comment by bennyhuo** [comment]
7 文案已经写完。
目测 5 和 7 需要各拆成 3 个视频，容量有点儿大。到时候具体再看吧

**Comment by bennyhuo** [comment]
本系列视频已经更新完毕，大家有问题可以留言，也许可以再搞几个出来✔
