### ISSUE TITLE
JetPack Compose 相关

### ISSUE THREAD

**Issue by bennyhuo** [bennyhuo/Kotlin-Tutorials#26]
等我稍微有点儿空的时候集中学习一下，现在也只是大概了解。

相关：Kotlin IR

**Comment by Richyeoh** [comment]
我也来占坑

**Comment by xiazunyang** [comment]
期待一波。:-)

**Comment by yasuofenglei** [comment]
# 占坑没带纸

**Comment by pr1n** [comment]
我都支持。

**Comment by bennyhuo** [comment]
Compose 开始支持 Web 了。https://blog.jetbrains.com/kotlin/2021/05/technology-preview-jetpack-compose-for-web/

**Comment by Richyeoh** [comment]
可以进入kotlin compiler plugin

**Comment by bennyhuo** [comment]
短期内应该不会规划 Compose 相关了，因为我不想学，哈哈。。。先关了
