### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by CodingPapi** [bennyhuo/Kotlin-Tutorials#3]
我也在试用Kotlint做开发，还没有放到生产环境。
我觉得还可以在你的目录中补充下注解相关的内容，以及Dagger2的使用。
最近我在翻译一部分kotlin的文章，我们可以一起合作  :)

**Comment by bennyhuo** [comment]
好呀~
注解相关的内容你是指注解处理器相关的内容？Dagger2 这样的框架确实值得一讲，我甚至考虑后续专门开贴讲，注解处理这块儿确实跟Java还是不太一样，应该安排一期，谢谢你的建议！

**Comment by CodingPapi** [comment]
kotlin的注解使用有一些坑，我对它的实现方式也很好奇 :)

**Comment by bennyhuo** [comment]
你说的类似 dagger，ButterKnife 这类的注解注入的框架的实现是吧？其实就是在编译期通过注解处理器的调用来生成一部分额外的代码来完成实例化、注入等一些操作的，这个确实是一个 Kotlin 与 Java 有明显不兼容的地方

**Comment by bennyhuo** [comment]
注解在 Kotlin当中的应用目前还是很局限，我最近准备出一期介绍介绍，有好的建议和想法直接发邮件给我吧！ bennyhuo@println.net

**Comment by bennyhuo** [comment]
注解视频将在今天发出~~
