### ISSUE TITLE
有趣的工具

### ISSUE THREAD

**Issue by bennyhuo** [bennyhuo/Kotlin-Tutorials#30]
- [x] [httpreq 介绍](https://www.bilibili.com/video/BV1bv41157xH/)，该工具可以方便地对接口进行测试 https://httpreq.com/  制作中
- [x] [Pipedream 介绍](https://www.bilibili.com/video/BV13h411v7Fr/)，该工具实现更复杂的接口调试场景，可以自定义请求结果，还可以把请求数据存起来。

**Comment by bennyhuo** [comment]
转至 #28 跟进

**Comment by Airomeo** [comment]
大佬，https://httpreq.com/ 失效了，有没有替代品？

**Comment by cys138138** [comment]
您好，你的邮件我已收到！
