### ISSUE TITLE
撸一些小程序

### ISSUE THREAD

**Issue by yasuofenglei** [bennyhuo/Kotlin-Tutorials#33]
可以考虑带着我们撸一些实用的小工具.在实践中使用kotlin的特性.

**Comment by bennyhuo** [comment]
具体一点儿？

**Comment by yasuofenglei** [comment]
> 具体一点儿？

比如先撸一个idea插件。您看如何？

**Comment by bennyhuo** [comment]
我也不会。。。。而且也太小众了吧。。。能整点儿阳间的不，工期不要超过一天的，😏&nbsp;

--------------原始邮件--------------
发件人："yasuofenglei ***@***.***&gt;;
发送时间：2021年6月1日(星期二) 晚上7:17
收件人："bennyhuo/Kotlin-Tutorials" ***@***.***&gt;;
抄送："Bennyhuo ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [bennyhuo/Kotlin-Tutorials] 撸一些小程序 (#33)
-----------------------------------

 

  
具体一点儿？
  
比如先撸一个idea插件。您看如何？

**Comment by bennyhuo** [comment]
不如带着大家刷题吧，哈哈哈

**Comment by yasuofenglei** [comment]
> 不如带着大家刷题吧，哈哈哈

真是个机灵鬼。这下好多期的视频都有了。不知道出什么就刷题。

**Comment by bennyhuo** [comment]
这个 issue 我关掉吧，有相关想法可以到 #35 下面评论。如果有其他语言的需要，再单独开 issue
