### ISSUE TITLE
Android Studio Profiler 网络监听功能是如何在给 okhttp 库添加 OkHttp3Interceptor 的

### ISSUE THREAD

**Issue by dzzchao** [bennyhuo/Kotlin-Tutorials#34]
由于在使用阿里云OSS上传SDK的时候遇到了 Stream  Close 的问题。
在网上找到了解决办法， 但开关不好使。 文章链接：https://www.jianshu.com/p/3608630af86a

但大概知道是由于添加了 com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor  这个拦截器导致的问题，想知道这个拦截器是怎么添加进去的？

**Comment by bennyhuo** [comment]
我用我的项目试了下，没看到这个拦截器，不知道是不是特定android系统版本才有?或者可以的话帮忙搞一个复现的demo，我可以抽空研究下哈

--------------原始邮件--------------
发件人："Shadow ***@***.***&gt;;
发送时间：2021年5月24日(星期一) 下午3:16
收件人："bennyhuo/Kotlin-Tutorials" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[bennyhuo/Kotlin-Tutorials] Android Studio Profiler 网络监听功能是如何在给 okhttp 库添加 OkHttp3Interceptor 的 (#34)
-----------------------------------

 

 
由于在使用阿里云OSS上传SDK的时候遇到了 Stream  Close 的问题。
 在网上找到了解决办法， 但开关不好使。 文章链接：https://www.jianshu.com/p/3608630af86a
 
但大概知道是由于添加了 com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor  这个拦截器导致的问题，想知道这个拦截器是怎么添加进去的？

**Comment by dzzchao** [comment]
试了几次没复现到具体出现的原因😫
