### ISSUE TITLE
Reactive和函数式编程

### ISSUE THREAD

**Issue by 0zyt** [bennyhuo/Kotlin-Tutorials#38]
老师在 https://www.bilibili.com/video/BV11b4y1Z7sz 这期视频中提到了RxJava（Reactive编程）和函数式编程，这两者之间除了看起来像（指写起来是链式），还有什么内在联系呢？Reactive和异步编程有什么关联?希望老师可以讲讲~

**Comment by bennyhuo** [comment]
怎么关了哈哈
