### ISSUE TITLE
建议在操作的时候 提一下按的快捷键

### ISSUE THREAD

**Issue by Sum41forever** [bennyhuo/Kotlin-Tutorials#5]
讲的很好，有点好奇 算命仙到底叫啥

**Comment by bennyhuo** [comment]
哦哈哈！快捷键是吧！可以的哈，我下周在公众号推一篇快捷键的文章吧，你觉得咋样！

**Comment by Sum41forever** [comment]
谢谢拉大大 你讲的这种形式 感觉很不错 时间短，知识点多。
  
         你说的专门出讲快捷键的文章，我觉得其实不用，一是这文章很多，二是看了没在实战中用记不住。
         建议你在讲视频的时候，提一下，看视频的人自己敲的时候，会去尝试的，这种效果会比较好。
        
         看了你的视频和文章有几个问题像请教。
         1. 你在写代码的时候，写完马上看编译出来的源码是怎么做的，是用的JD-IntelliJ 的反编译插件吗？Android Studio下也可以用吗？
       
         2. 《我和Gradle的约会》这文章中，AS编译速度很慢，你说的三个参数，我在gradle.properties里都加过。但是效果不是特别明显。
       我的task每次都会同时编译很多个Task。我知道Gradle能写编译脚本。有没有这方面的文章推荐下
       以前有个项目比较大超过10W的方法，编译很慢，一般是5-6分钟，慢一点10多分钟都有，后来把依赖库打成AAR了，速度快1分钟多。你在开发中有遇到这个问题吗？有什么建议？
![12](https://cloud.githubusercontent.com/assets/18468976/21680962/c0dc2e96-d387-11e6-9989-879cf16f8170.png)

**Comment by bennyhuo** [comment]
1. 快捷键具体是什么确实讲了也没啥意思，就像你说的，文章也很多，也记不住。关于这块儿我可能也是跟视频差不多的风格，会想一些比较有意思的点介绍一下。

2. 看编译出来的，你是指看.class吗？还是说看字节码？如果是看字节码，kotlin自带了kotlin的字节码工具比较好用，在菜单 Tool -> Kotlin -> Show Kotlin Byte Code；如果是看 Java的，有个 ASM ByteCode Outline ，安装完重启 IntelliJ， 在 Java或者Kotlin文件上面右键看到 show bytecode outline 就是这个插件的功能。

3. gradle 确实慢呐。。。不过一般对于大项目，编译也是采用增量编译的，除非你改动比较多，第一次编译会比较久，一般后面的编译基本上也就一两分钟吧。aar的这种形式是比较推荐的方式，不过android 最终会有个 打dex的步骤，这个步骤能耗去 90% 的时间，而且对于 5.0 以下的版本是无法跳过的，所以如果你为了加快开发，可以自定义一个 flavor，把debug 的targetSDKVersion 设置为 21。这是因为 5.0 以上的安装包会允许安装包有多个 dex文件，所以就不会有最后那一步最耗时的dex了。

**Comment by Sum41forever** [comment]
刚看了Rxjava Retrofit 那部分 讲的很好。自己看的文档中有些不明白的地方都清楚了。
大大的名字 我知道了确实玄学，之前看腾讯Bugly有篇文章好像是讲Retrofit的 就是大大写的吧。

希望有机会能出视频 讲讲Rxjava容易掉坑的地方和一些看Android源码的经验。比如事件发射。之前都觉得是一个事件流，深入源码看的晕头转向。看了你的视频一下豁然开朗。很多想法写代码写不出来。可能还是经验太少了。

**Comment by bennyhuo** [comment]
RxJava 我刚用了半年多，还没有时间深入源码，等我研究一段时间可以考虑发视频出来。短时间内我就在 Kotlin这个公众号上面发文文章了，每周最少发一篇 Kotlin 相关的，另外看精力在发点儿别的文章~

之前经常会有一些文章发到 Bugly 上面，后来写得少了。另外之前的文章也是比较零散，后面应该会花挺多精力在 Kotlin上面。

经验这种事情不能心急，只要你经常思考，每隔半年回想一下自己半年对代码的认识，你就会发现你自己成长很快了。

谢谢你的支持，有什么需求也可以尽管提出来，有些东西我不懂的也可以顺势学习一下分享给大家。大家一起努力吧~

**Comment by bennyhuo** [comment]
快捷键的文章，确切的说不止是快捷键了，这篇文章主要介绍了一些 IntelliJ 几个有用的但大家不一定想得到的使用技巧，明天公众号记得给我点赞转发哈~

**Comment by Sum41forever** [comment]
谢谢大大，今天在掘金上看到了。我把你的文章转到到了我的笔记。
在你发的内容上做了些整理。添加了部分操作在Window的快捷键
我能公开么？我著名了转载自你的网站。

**Comment by bennyhuo** [comment]
没有问题，发了之后给我瞅瞅~

**Comment by bennyhuo** [comment]
可以关注下公众号 Kotlin，我的文章都在这里推送

**Comment by Sum41forever** [comment]
关注了的。文章在这里。
http://sum41forever.leanote.com/post/19346e077927
笔记用的你用的呢 - -！之前用的有道云笔记 感觉没你用的好。我就这几天开始用你博客用的那个了。
汗 好多东西 都是从你博客学过来的。- -！
之前就觉得 我逻辑太差 后来从你博客看到leetcode 周末的时候 就去玩了下。感觉挺有意思
kotlin正在学。昨天花了一天时间才跑起来程序。
从来没用过Intellij，感觉和AS还是有些不一样。总结下我遇到的坑 

坑1：Unindexed remote maven repositories found  http://repo1.maven.org/maven2 这个地址无法更新。
![2223](https://cloud.githubusercontent.com/assets/18468976/21791613/f8246090-d71e-11e6-82ce-a992eef5651e.png)
![222222](https://cloud.githubusercontent.com/assets/18468976/21791615/f86b7ade-d71e-11e6-868f-47b74b93e6e2.png)

gradle用的mavencenter()一直连不上，虽然知道可以用Jcenter().
但是还是花了很多时间想去解决这个问题，找了好多最后换了几个镜像地址。还是不行。

PS：突然理解去年刚工作时前辈给我说 能用jcenter就别用mavencenter()的原因了
stackoverflow上的相同问题留着当参考
http://stackoverflow.com/questions/32037082/unindexed-remote-maven-repositories-in-intellij-idea-14

坑2：无法编译文件 Cannot run program "C:XXXXX...compile-server"CreateProcess error=2
intellij好像自己有jre 默认是用自带的。在这里进入Structure 修改成Java Home 的jre
![qq 20170110102101](https://cloud.githubusercontent.com/assets/18468976/21791573/917d64c2-d71e-11e6-8a2b-3af8a922e2b8.png)

坑3： 无法运行程序。
![1111](https://cloud.githubusercontent.com/assets/18468976/21791689/94676ad8-d71f-11e6-8b41-c3c5e33ec4bd.png)
这是默认的情况，不能运行，要想运行要先在kotlin文件中 （PS：项目必须构建完成）
1.先点右键 执行recompile “xxxx.kt”
2.然后在点右键 执行Create'xxxx' ,然后就可以运行了。
（我住的地方没耳机，看视频很多时间是没声音...，这个可能视频里有讲过。）

![23](https://cloud.githubusercontent.com/assets/18468976/21791588/c0e62b40-d71e-11e6-9142-518bce37f5eb.png)

**Comment by bennyhuo** [comment]
真棒！给你的认真点赞~

坑1  maven 中央仓库经常被qiang，我刚接触maven的时候也因为这个相当崩溃，现在有了jcenter就挺好了。当然如果在公司，一般大公司比如阿里、腾讯都有自己的镜像，这个也不是问题。公网的 oschina的镜像还不错。

坑2 我不太知道了，可能也遇到过。

坑3 如果有main 方法，右键有main方法的这个类就可以有菜单直接运行的。

加油~

**Comment by bennyhuo** [comment]
有问题可以发邮件持续跟我讨论哈~我先关了这个issue了哈
