### ISSUE TITLE
关于 Telegram 群

### ISSUE THREAD

**Issue by wafer-li** [bennyhuo/Kotlin-Tutorials#9]
问一下有没有 Telegram 群呢？

QQ 毕竟对 Linux 不友好，聊天和文件也不能永久保存多端同步

**Comment by bennyhuo** [comment]
这个。。Telegram 没用过呀~

**Comment by bennyhuo** [comment]
额，试了下我在公司翻了墙都打不开 Telegram 的官网。。

**Comment by wafer-li** [comment]
😂 你可能翻的是假墙？
虽然 Telegram 的确要翻墙，不过翻了墙之后肯定是能顺利访问的啊。。。

**Comment by bennyhuo** [comment]
哈哈，在这个网站上面来看，是不完整的墙。现在上 qq 都用手机了，聊天和文件永久保存其实也没什么用吧，如果你不是在国外，qq 还是首选吧
